name: submark
version: '0.3.0'
synopsis: Extract a part from CommonMark/Markdown docs
category: Text
author: Hong Minhee
maintainer: hong.minhee@gmail.com
copyright: (c) 2017 Hong Minhee
license: GPL-3
github: dahlia/submark
stability: alpha
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- base >= 4.7 && < 5
- cmark >= 0.5.6 && < 0.6.0
- text == 1.*
flags:
  static:
    description: Static link
    manual: true
    default: false
ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
library:
  source-dirs: src
  dependencies:
  - regex-tdfa >= 1.3.1.2 && < 1.4
executables:
  submark:
    main: Main.hs
    source-dirs: app
    dependencies:
    - submark
    - optparse-applicative >= 0.13.2.0 && < 0.17.0.0
    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        # Static link
        - -static
        - -optl-static
        - -optl-pthread
        - -optc-Os
        - -fPIC
      else:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
    - hspec >= 2.4.4 && < 3.0.0
    - submark
    - template-haskell >= 2.5
  hlint:
    main: Main.hs
    source-dirs: lint
    dependencies:
    - hlint >= 2.0.9 && < 4
