resolver: nightly-2022-03-03
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
ghc-options:
  submark: -Werror

# https://github.com/commercialhaskell/stack/issues/5290
save-hackage-creds: false
