name: test-actions
on:
  push: []
  schedule:
  - cron: 59 14 * * *
  pull_request: []

jobs:
  test-setup-submark:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15
        - macos-11
        - windows-2016
        - windows-2019
        - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # Test 1
    - id: setup1
      uses: ./setup
      with:
        submark-version: 0.3.*
        add-to-path: false
    - run: |
        set -e
        [[ "${{ steps.setup1.outputs.submark-version }}" = 0.3.* ]]
        [[ "${{ steps.setup1.outputs.submark-version }}" != "0.3.*" ]]
        ! command -v submark
      shell: bash
    - run: >-
        ${{ steps.setup1.outputs.submark-path }}
        --h2 "software license"
        -i README.md
    # Test 2
    - id: setup2
      uses: ./setup
      with:
        submark-version: 0.3.0
    - run: |
        set -e
        [[ "${{ steps.setup2.outputs.submark-version }}" = "0.3.0" ]]
        command -v submark
      shell: bash
    - run: 'submark --h2 "software license" -i README.md'
    - run: >-
        ${{ steps.setup2.outputs.submark-path }}
        --h2 "software license"
        -i README.md

